name: gs_reflection
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.7.13
  - pip=22.3.1
  - pytorch=1.13.1
  - cudatoolkit=11.6
  - torchvision=0.14.1
  - torchaudio=0.13.1
  - pytorch-cuda=11.7
  - plyfile
  - tqdm
  - pip:
    - submodules/cubemapencoder
    - submodules/diff-gaussian-rasterization
    - submodules/diff-surfel-rasterization
    - submodules/simple-knn
    - submodules/fused-ssim
    - opencv-python
    - joblib
    - matplotlib
    - tensorboard
